services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: syncai/backend:latest
    container_name: syncai-backend
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - PYTHONPATH=/app
      # AnythingLLM 配置 - 從容器內訪問主機服務
      - ANYTHINGLLM_BASE_URL=http://host.docker.internal:3001
      - ANYTHINGLLM_API_KEY=PNB2B7R-4EC4P21-NM0XHTX-4BHZBHJ
      - ANYTHINGLLM_WORKSPACE_SLUG=syncai
      - ANYTHINGLLM_DEBUG_THINKING=false
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 允許容器訪問主機服務
    # volumes:
      # - ../ai_models:/app/ai_models:ro  # 已移除本地模型目錄掛載
    restart: unless-stopped
    networks:
      - syncai-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    image: syncai/frontend:latest
    container_name: syncai-frontend
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - syncai-network

networks:
  syncai-network:
    driver: bridge
