services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: syncai/backend:latest
    container_name: syncai-backend
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../ai_models:/app/ai_models:ro  # 將本地模型目錄掛載到容器中（唯讀）
    restart: unless-stopped
    networks:
      - syncai-network

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    image: syncai/frontend:latest
    container_name: syncai-frontend
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - syncai-network

networks:
  syncai-network:
    driver: bridge
